# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main  # or your branch name

pool:
  name: Default

steps:
  - task: Maven@4
    inputs:
      azureSubscription: 'Azure for Students(1)(5bcf5fc2-d7fe-4e16-8817-9f688375aa3f)'
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkDirectory: 'C:\Program Files\Java\jdk-23'
      mavenVersionOption: 'Path'
      mavenDirectory: 'C:\Users\ASUS\apache-maven-4.0.0-rc-3\bin'
      mavenSetM2Home: false
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
